apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bq-monitoring

resources:
  - cronjob.yaml

images:
  - name: bq-deep-check
    newName: code.blockchain-applied.com/bca/bq-deep-check
    newTag: "1.0.1"
